# Generated by Django 6.0.1 on 2026-03-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('mail', models.EmailField(max_length=254)),
                ('contact_number', models.IntegerField()),
                ('bio', models.TextField()),
            ],
        ),
    ]
